### ISSUE TITLE
Grim Fandango isn´t recognized

### ISSUE THREAD

**Issue by MysticFlipFlop** [libretro/scummvm#18]
Description
i tried to scan Grim Fandango (Spanish) because i read that residualvm was merged into scummvm. But it says no game was found in the folder. This is only a problem only on wii u core. I tried the same on the pc core and it was succesfully added to ScummVM Launcher.

Expected behavior
The game should be detected and added to ScummVM Launcher

Actual behavior
The core says there is no game and can´t be added to ScummVM Launcher

Screenshots
![3a41f](https://user-images.githubusercontent.com/113185836/225505622-8e328ebc-0a09-4aa1-a876-a3878f806f06.png)

Steps to reproduce the bug
Launch core with no content
Select Add Game
Search the folder where the game is located
Open the folder
Select Choose

Version/Commit
2.7

ScummVM game/engine

Environment information
Device: Wii u
OS: Tiramisu
Additional context
[Add any other context about the problem here]

**Comment by spleen1981** [comment]
`grim` support is not included for the wiiu build. which supports only a [limited engines list](https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/lite_engines.list) to limit the size of the bundle.

**Comment by Ploggy** [comment]
Out of curiosity what would the filesize be? the same as the PC Scummvm Core? .. which is 81.9MB.
I think the WiiU filesize would be smaller since it does compression when building the RPX but I don't know how much it would reduce the file size.. Also I don't think there is a size limit to launching WiiU HB RPX files.. 
Would it be possible to do a one off build as a full bundle? Just to see if it works at all? :)

**Comment by spleen1981** [comment]
Frankly speaking I have no idea of what's the specific size limitation, this build setting is coming from the legacy core and I assumed there was some reasoning behind it.
Anyway it's easy to check having a wiiu handy what's wrong with the full list, you just test [artifacts ](https://git.libretro.com/libretro/scummvm/-/jobs/3307940) from `wiiu_extended` branch and let me know.

**Comment by Ploggy** [comment]
Hmm, perhaps your right, there is a reason why it was limited in the legacy core :P 
The core fails to load in Retroarch, It just shows "an error has occurred. Press and hold the power button for 4 seconds to turn the console off" screen :/
Though the core is only a couple MB larger than the next biggest core FBNeo, so I don't know for sure if the error is size related.

But it doesn't work either way.. Thank You for letting me test it out anyway :)

As for the Grim Fandango issue could you remove just Grim from the limited engine list?

**Comment by spleen1981** [comment]
That "lite" list is there for legacy reasons and it's not going to be maintained / updated in the official tree (also because adding one engine and not one another is questionable).
Anyway users can clone the repo, modify [the list](https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/lite_engines.list) and compile their own custom builds.

**Comment by Ploggy** [comment]
Ok that's fair enough :)
