### ISSUE TITLE
DreamWeb cd/floppy doesn't work

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#20]
Dreamweb does not work. I tested both cd and floppy versions.
The Dreamweb freeware version can be found on the scummvm website:
https://downloads.scummvm.org/frs/extras/Dreamweb/dreamweb-uk-1.1.zip

I get this error when trying to run game:

![Bez tytułu](https://user-images.githubusercontent.com/123302593/226130061-bcb0f5bc-8289-42b4-9958-1e24c20ee5e3.png)

Retroarch 1.15
Scummvm 2.8.0 git
My pc: Win 11, I7 8700k, rtx 3070ti

@spleen1981 please could you fix this problem?
I will be very grateful. DreamWeb is one of my favorite games.

**Comment by i30817** [comment]
Same here.

**Comment by spleen1981** [comment]
fixed by 784a6edb1a35e30c9198ac6ec94ba41f6a453b4c

**Comment by i30817** [comment]
I wanted to test this but it seems the latest core at https://buildbot.libretro.com/ doesn't have it yet, in spite of being built a few minutes ago.

It's still ba1567f-2.8.0-git, which is from 8 hours ago. Wait until tomorrow to test then.

**Comment by KamiLordus** [comment]
@i30817 can be downloaded from here:
https://git.libretro.com/libretro/scummvm/-/pipelines

@spleen1981 I tested both versions and they work fine.
Thank you for solving the problem.

**Comment by i30817** [comment]
I was trying this game and in the second location (Ryan's apartment) when you have to use the computer, the keys read weirdly even when you have game focus mode on.

It sometimes puts in two keys one of which is not near what i pressed. Like i press 'P' and it immediately outputs 'P8'.

**Comment by i30817** [comment]
The save games also have corrupted names in the ingame menu.

**Comment by KamiLordus** [comment]
I saved the game and didn't notice any issues (game focus on). If you send me a save, I will check the computer you mentioned.

**Comment by i30817** [comment]
The savename name corruption is obvious here (in linux 64 bits):
![image](https://user-images.githubusercontent.com/757900/227751172-0c1bdf52-b68d-4744-956b-1902a1e02ef6.png)

For the computer save (load 'monitor bug'):
[DREAMWEB.zip](https://github.com/libretro/scummvm/files/11070594/DREAMWEB.zip)

Just 'use' the monitor ('network screen') in the corner nearest you, and when the monitor gives you input, press 'p' or 'l', they will add numbers besides the letter. You can still progress because you can delete the number before pressing a new key.

It's possible that this is because i'm using the keyboard as 'retropad' and i have the 'right analog' mapped, which uses the keys 'p' (up), 'ç' (down, retroarch reports it as 'semicolon', which btw, it isn't), 'l' (left), 'º' (right, retroarch reports it as 'quote').

I'm in linux wayland, so i'm using the wayland input driver, with game focus mode to on, but that doesn't matter.

**Comment by KamiLordus** [comment]
Without using original save/load I also have such squares on save. But that's all I noticed. Typing from the keyboard and the on-screen keyboard works fine. I'm using Win 11 and xbox one controller.

**Comment by i30817** [comment]
I'm not sure of the definition of original save/load. I use the game menus until it's actually time to save or load, then scummvm redirects me to the screen i showed. So i guess i'm 'not' using the originals (edit: with the original save/load screens enabled in the scummvm game options they show fine so...).

Also the monitor thing was because of the mapped L-stick buttons. I disabled them in the retroarch menu for the game and it no longer happened. It's a bit strange that game focus prevents that for 'other' bounded retroapad keys but not those though.
