### ISSUE TITLE
Riven cursor problem

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#22]
Riven (DVD Windows) - the cursor has a large black square

![Bez tytułu](https://user-images.githubusercontent.com/123302593/227776817-5efde858-1cc4-4125-8f5a-3563ee1c1959.png)

RA 1.15
Win 11 Pro

**Comment by spleen1981** [comment]
Were those working before?

**Comment by KamiLordus** [comment]
Blade Runner was still working a day/two ago (100% sure)
Unfortunately, I can't say about the rest. Riven and Myst - Masterpiece were last launched a month ago.

Edit:
I can also add:
Myst and Riven definitely work without bugs on 2.6.1.4-7 (the only older version I have and checked).

**Comment by KamiLordus** [comment]
I can also add:
Myst and Riven definitely work without bugs on 2.6.1.4-7 (the only older version I have and checked).

**Comment by spleen1981** [comment]
ok, it's a regression due to the latest Dreamweb fix, 5f93be7d97bcb768338e7faca9bb4768c6fb5f87 reverts that, Myst and Blade Runner should be working now.
7d6f2ced5037e43e0f245cdedb07d4e1bc9edc2d is the new fix for Dreamweb.
Riven cursor looks like a separate issue.

**Comment by KamiLordus** [comment]
I tested the latest version 3a132f72
Dremweb works very well
Blade Runner image is back
Myst Masterpice - works very well.

I'll edit the post and leave only Riven
Thank you very much for the bug fix.

**Comment by i30817** [comment]
Cursor in riven and myst and 11th hour and starship titanic was a old bug that also existed the diablodiab core.


https://github.com/diablodiab/libretro-scummvm-backend/issues?q=is%3Aissue+myst+is%3Aclosed

not sure if the same thing. Anyway, the cause is explained in the issue linked with a patch to the problem (then).

**Comment by i30817** [comment]
Opps wrong link. It's:  https://github.com/diablodiab/libretro-scummvm-backend/issues/3

**Comment by i30817** [comment]
Mmm. No i don't think it's the same anymore. The patch is already applied to libretro-os.cpp and of the games i mentioned, only riven has the problem.

**Comment by KamiLordus** [comment]
@i30817 In version 2.6.1.4-7 of 02/26/2023, Riven has no cursor bug. I'm pretty sure it wasn't in later 2.7.0 git either. The bug appeared in some version 2.8.0.

@spleen1981 we go back to version 75051b55 without the Dremweb fix?

**Comment by spleen1981** [comment]
> we go back to version https://github.com/libretro/scummvm/commit/75051b551db89b5a9ede3f35b75fcf49cd3483fe without the Dremweb fix?

Check the previous commit https://github.com/libretro/scummvm/commit/7d6f2ced5037e43e0f245cdedb07d4e1bc9edc2d, that's the fix.
Then there is also a separate PR pending for that engine, regarding how titles are displayed. https://github.com/scummvm/scummvm/pull/4848

**Comment by asciibeats** [comment]
Blade Runner works again for me when i strip down the function splashScreen() in engines/engine.cpp to:
```
void splashScreen() {
  g_system->showOverlay();
  g_system->updateScreen();
  g_system->hideOverlay();

  splash = true;
}
```

**Comment by asciibeats** [comment]
Apologies. Did not read [the comment](https://github.com/libretro/scummvm/issues/22#issuecomment-1484250247) :+1:

**Comment by i30817** [comment]
I'm not even sure if i should mention this, but there is a random crash on the longest journy, although it takes a long time to trigger and i'm not sure if it's not upstream too. Reloading the last save prevents it.

Apologies because i closed the command console where it happened. It mentioned a 'linear allocator' failure. I didn't get a stacktrace.

I also noticed small graphics bugs on the game although those are minor.

**Comment by KamiLordus** [comment]
@i30817 Maybe try opening a separate ticket.
Some time ago I tried Longest Journey and so far the graphical errors are quite disturbing (for example, a character surrounded by a rainbow of colors).

**Comment by i30817** [comment]
There are 4 graphical errors i noticed (of course, this is all in software renderer mode, because i'm playing the scummvm libretro core, which might affect things). 

- The 'rainbow dots in certain scenes around the main character' you mentioned.
- The 'shadow defect' in the scene in stark where you're supposed to move a road block and the roadblock has a anomalous shadow that paints over the main character if it's on front of it (which makes no sense)
- Several places where character animations have the wrong orientation, like how the 'head priest' of the religion in arcadia which you meet the first time you go there has a 'backwards from the podium' pose as if already facing the MC when you go talk to him repeatedly but instantly turns around to be reading a book from the podium before turning around to the original position if you actually talk to him. And several places where the MC when talking to a character is 'oriented wrong' when she does the animation, usually a sitting or crouching one, i happens often when you talk to the legless guy on the hoverchair near the end game.
- And a place in the roper klacks alchemist castle where you could get stuck outside of pathfinding bounds if you entered a door while running (i think) and got stuck during the exit animation outside of bounds.

The 'linear allocator' thing i didn't manage to trigger in debug, but it usually takes a long time playing so i'm not sure if it wouldn't be possible. It's a 'tinygl' thing, a library that scummvm uses to abstract opengl 'platform specific' work.

**Comment by KamiLordus** [comment]
Today I turned on Riven and noticed that the problem with the cursor disappeared. So I'm closing the ticket.
I tested both CD and DVD versions.
![Bez tytułu](https://user-images.githubusercontent.com/123302593/230958925-7cd2aa5e-2e93-4951-aa68-41cfd082c2a8.png)
