### ISSUE TITLE
Command line not working

### ISSUE THREAD

**Issue by ToniBC** [libretro/scummvm#27]
When trying to run the scummvm core from the command line (in retroarch for Windows), it doesn't work, retroarch closes itself and this makes it unable to integrate with launchers.

For example, if we put:

retroarch.exe -L cores/scummvm_libretro.dll

This should launch the core with the interface, but it tries and does nothing.

But if we put another similar core, like dosbox pure.

retroarch.exe -L cores/dosbox_pure_libretro.dll

Here everything runs smoothly.

On the other hand, if we drag a .scummvm file to the executable, it does work, but not by commands and this means that it cannot be integrated into launchers.

Thank you.

**Comment by i30817** [comment]
Also happens in linux.

**Comment by spleen1981** [comment]
fixed by 1d1fa646d0c763c259b4e8dd42caa5ffac602bf6

**Comment by spleen1981** [comment]
@ToniBC is this confirmed to be fixed now?

**Comment by i30817** [comment]
It's fixed in linux anyway.

**Comment by i30817** [comment]
I'm sure you know, but there is a segmentation fault when quitting the core from the scummvm gui quit button (not 'close core' or quit retroarch from the retroarch menu).

I also found a weird way to put the core into windowed no-decoration mode in GNOME wayland by pressing alt+f5 but I think that's from wayland since i disabled the toggle fullscreen shortcut (and all f5 buttons) in the retroarch.cfg, and retroarch doesn't support combinations anyway. Weirdly, pressing it again doesn't restore fullscreen. GNOME is being weird about this one.

**Comment by ToniBC** [comment]
Yes, it works now without problems, sorry for the delay in answering.

Thank you so much.
