### ISSUE TITLE
Broken Sword - No speech

### ISSUE THREAD

**Issue by WDeranged** [libretro/scummvm#49]
I'm using the original English CD release.  It is correctly packaged and works properly using the stand alone version of ScummVM.

**Comment by i30817** [comment]
Did you use the new playlist creator? Sometimes it makes a difference.

**Comment by WDeranged** [comment]
I don't use Retroarch playlists for ScummVM.  I just add games in the core through the menu.

**Comment by i30817** [comment]
That's enough, it's (almost) the same thing, I was mentioning what the RetroArch readme said about the core (not adding the games through the scummvm menu then invoking it through .scummvm files with the bare engine name instead of a scummvm.ini entry name).

I don't have access to my game files right now to test it.
Only thing I can think of then is that you rencoded the audio and scummvm supports that format while the core doesn't,  presumably because of a library dependency missing.

**Comment by WDeranged** [comment]
I'm using files directly from the original european CD.  I have tried other versions that have re-encoded audio but the result is the same.  It does seem like there a missing codec.

**Comment by spleen1981** [comment]
My copy is working properly, did you check info [here](https://wiki.scummvm.org/index.php/Broken_Sword_1)?
In particular :
> Note: Since ScummVM 2.7.0 the folder structure from the original media needs to be preserved. Older versions of ScummVM allowed to move files to the top level folder, while they now need to remain in their respective subdirectories. If your game is no longer detected by ScummVM, you may need to move back the files to their original subdirectories. 

Anyways the core is generally more updated than standalone releases, a better comparison is against their 'daily builds'.

**Comment by KamiLordus** [comment]
The game works properly and the report can be closed.
Since version 2.6.0, scummvm supports the creators of old adventure games, whose games can be found on gog.com.
The soundtrack file must be in the new format, which is available on gog. Pirated versions of the game have an old soundtrack format that is no longer supported - that's why there are no dialogues.
Here is a related topic from the game Full Throttle from the scummvm forum.

**Comment by spleen1981** [comment]
I assume this can be closed...
